### ISSUE TITLE
Duplicate ID values on login and register forms

### ISSUE THREAD

**Issue by leeoocca** [testsmith-io/practice-software-testing#439]
When the password input wrapper component `<app-password-input>` is created, it's given an ID of value `password`.

https://github.com/testsmith-io/practice-software-testing/blob/86879ed51c2456b679029cc8627056b4d069165b/sprint5/UI/src/app/auth/register/register.component.html#L245

The same value is then also set to the actual `input` element:

https://github.com/testsmith-io/practice-software-testing/blob/86879ed51c2456b679029cc8627056b4d069165b/sprint5/UI/src/app/shared/password-input/password-input.component.ts#L17

This creates two elements with the same ID on the login and register pages:

- https://practicesoftwaretesting.com/auth/login
- https://practicesoftwaretesting.com/auth/register

The output of `$$("#password")` in the console is the following for both pages:

```js
Array [ app-password-input#password.ng-untouched.ng-pristine.ng-invalid, input#password.form-control ]
```

**Comment by testsmith-io** [comment]
Thanks for the bug report! 

I will fix it ASAP, or would you help and open a PR?
